In [ ]:
import numpy as np

#come matlab, genero un array di valori equamente distruiiti
arr_prova = np.linspace(10, 49, 1)
arr = np.arange(1, 13).reshape(3,4)
print(arr)

#arr = arr.astype(np.float64)    #cambio tipo in float64

print(arr.dtype)    #stampo il typo

print(arr.shape)    #stampo la forma


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
float64
(3, 4)


In [ ]:
import numpy as np
import random as rd

array = np.array([rd.randint(10, 50) for i in range(20)])   #returno 20 valori casuali tra 10 e 50 con la comprehension list
array = np.random.randint(10, 50, 20)   #returno 20 valori casuali tra 10 e 50 con la funzione randint
print(array[0:10])   #stampo primi 10

print(array[15:20])    #stampo ultimi 5

print(array[5:15])    #stampo dal 5 al 15
array[5:10] = 99    #da indice 5 fino a 10 escluso assegno il valore 99 

print(array)    #stampo l'array modificato






In [2]:
import numpy as np
dim = 6
array = np.random.randint(1, 100, (dim, dim))   #creo array 6x6 con valori casuali tra 1 e 100
#oppure
#array = np.array([np.random.randint(1, 100, dim) for i in range(dim)])

array4x4 = array[1:5, 1:5]   #estraggo un array 4x4 dall'array 6x6, il 5 è escluso

#uso variabile di swap per invetire le righe
swap = array4x4[0, :]
array4x4[0, :] = array4x4[3, :]
array4x4[3, :] = swap
swap = array4x4[1, :]
array4x4[1, :] = array4x4[2, :]
array4x4[2, :] = swap

diagonale_principale = array4x4.diagonal() #estraggo la diagonale principale dell'array 4x4

for i in range(array4x4.shape[0]):
    for j in range(array4x4.shape[1]):
       if array4x4[i, j] % 3 == 0:
            array4x4[i, j] = -1

#stessa operazione con con slicing, qui si usa il boolean indexing
array4x4[array4x4 % 3 == 0] = -1

print(array)
print(array4x4)
print(diagonale_principale)

[[84 98 22 75 61 10]
 [23 16 89 28 -1 90]
 [36 55 -1  2 -1 64]
 [90 55 -1  2 -1 51]
 [38 16 89 28 -1 23]
 [77 81 56 60  4 21]]
[[16 89 28 -1]
 [55 -1  2 -1]
 [55 -1  2 -1]
 [16 89 28 -1]]
[16 -1  2 -1]


In [ ]:

while True:
    file = open("array.txt", "w+")   #apro il file in scrittura e lettura, se non esiste lo creo
    
    array = np.linspace(1, 10, 50)   #genero 50 valori equamente distribuiti tra 1 e 10

    array_casuale = np.random.randint(1, 10, 50)   #genero 50 valori casuali tra 1 e 10

    vettore_somma = array + array_casuale   #somma vettoriale

    print(np.sum(vettore_somma))   #somma di tutti gli elementi del vettore somma


    somma_more_than_five = np.sum(vettore_somma[vettore_somma > 5])   #somma di tutti gli elementi del vettore somma maggiori di 5

    selezione = input("Vuoi sovrascrivere il file? y/n")
    if selezione == "y":
        file.write(str(array) + "\n")   #scrivo l'array nel file
        file.write(str(array_casuale) + "\n")   #scrivo l'array casuale nel file
        file.write(str(vettore_somma) + "\n")   #scrivo il vettore somma nel file
        file.write(str(somma_more_than_five) + "\n")   #scrivo la somma degli elementi maggiori di 5 nel file
        file.close()



50
